# Generated by Django 4.2 on 2024-11-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Puntos', models.IntegerField()),
                ('Usuario', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreUsuario', models.TextField(max_length=255)),
                ('Correo', models.TextField(max_length=255)),
                ('Password', models.TextField(max_length=255)),
            ],
        ),
    ]
